### ISSUE TITLE
Внешний вид редактора

### ISSUE THREAD

**Issue by arykovs** [llownall/wysiwygMath#1]
Сделать такой: 

![Clipboard05](https://user-images.githubusercontent.com/20451590/96333697-a9361f00-1095-11eb-9dea-d5a6cfa0c3b8.jpg)

- [x] Кнопку H для заголовков убрать. Кнопки A+ и A- заменить на выбор размера шрифта в пунктах. 
- [x] Для кнопки с формулой использовать square-root из fontawesome, для иконки вставки изображения - image.

**Comment by llownall** [comment]
> * [x]  Для кнопки с формулой использовать square-root из fontawesome, для иконки вставки изображения - image.

Почему-то иконка `<i class="fas fa-square-root-alt"></i>` не отображается, хоть и бесплатная.

**Comment by arykovs** [comment]
1. Есть разные части fontawesome, которые можно подключить. В зависимости от этого не все иконки будут доступны. Если вы подключите https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css - тогда иконка корня появится. Нужно разобраться в этом вопросе и подключить минимально необходимый набор иконок, чтобы не грузить на страницу лишнего, но чтобы все, что нам нужно - работало. Либо может у вас версия не та подключается.
2. Нужно, чтобы тулбару при запуске передавался набор параметров - кнопок, которые отображать. Пока давайте скроем кнопку вставки изображения.
3. Тулбар, который на https://llownall.github.io/ не соответствует картинке выше. Там нет возможности выбрать размер шрифта и присутсвуют кнопки smaller, bigger (их можно тоже полностью не удалять, а отключить через параметры).

**Comment by arykovs** [comment]
- [x] Подергивание (изменение ширины) в Firefox:
1. Открыть llownall.github.io в Firefox
2. Кликнуть мышкой на поле редактирования. Появится редактор.
3. Перевести мышку на редактор, на кнопку B. Дальше сдвинуть мышку на букву I и потом - на U. Видно, что когда гаснет подсветка B - тулбар немного увеличивается в ширину. Когда загорается подсветка I - он опять возвращается к исходной ширине. Таким образом, когда ведешь мышку от левого края к правому - происходит постоянное подергивание.

**Comment by arykovs** [comment]
Выделение кнопок на тулбаре:
- [x] Давайте сделаем, чтобы размер выделения не зависел от кнопки (был для всех одинаковый). Сейчас размер прямоугольника-подсветки для буквы I заметно меньше, чем для S, например. 
- [x] Давайте попробуем убрать рамку вокруг прямоугольника-подсветки. Кажется, что без нее будет лучше, но надо попробовать, чтобы убедиться.
- [x] Сейчас подсветка делается только для некоторых кнопок (B, I и др.), но не работает для обоих кнопок списков, выбора формулы и отмены действия. Давайте сделаем подсветку для всех кнопок.

**Comment by arykovs** [comment]
- [x] При нажатии на кнопку тулбара (например, кнопку B) теперь вокруг нее появляется и исчезает черная рамка (Chrome), либо появляется и не исчезает пунктирная рамка (Firefox). Надо убрать это.

**Comment by arykovs** [comment]
- [x] Допустим, я выделяю некоторое слово и нажимаю кнопку B. Тогда к этому слову применяется шрифт 'жирный', но сама кнопка на тулбаре не становится 'нажатой'. Чтобы увидеть, что она нажата - надо передвинуть указатель мыши на другую кнопку. Давайте поправим. При клике на кнопку она сразу должна менять свое состояние, а не когда с нее уходит подсветка, как сделано сейчас.

**Comment by llownall** [comment]
> 2. Нужно, чтобы тулбару при запуске передавался набор параметров - кнопок, которые отображать. Пока давайте скроем кнопку вставки изображения.

Отображаемые иконки - массив `functions`. Будут отображены иконки для функций, упомянутых в массиве:
`<wysiwyg-math :functions="['textStyle', 'fontSize', 'textAlign', 'lists', 'imageInsert', 'formulaInsert', 'redo']></wysiwyg-math>`
