### ISSUE TITLE
Форматирование

### ISSUE THREAD

**Issue by arykovs** [llownall/wysiwygMath#11]
Открываю тестовую страницу, кликаю на поле ввода, дальше в появившемся тулбаре нажимаю B. Убираю с него курсор - B не нажата. Ввожу любой символ - тогда B становится нажатой, а символ вводится жирным. Должно быть так, что если я на тулбаре нажал B, то она и остается нажатой, даже если я еще не ввел ни одного символа.

Аналогичная проблема для других опция форматирования: I, U, S.

**Comment by arykovs** [comment]
Открываю новую страницу, кликаю на поле ввода, в появившемся тулбаре нажимаю B. Ввожу одно слово (любое). Дальше на тулбаре отключаю B. После этого нажимаю Enter. Курсор перехоит на новую строку, буква B опять зажата на тулбаре (ошибка), но текст набирается как и должно быть, не жирным.

**Comment by llownall** [comment]
После перехода на новую строку тег `<br>` обрамляется в `<b></b>` автоматически (не мною), а после ввода любого символа теги `<b></b>` исчезают. Получается, редактор анализирует структуру на месте курсора верно
