### ISSUE TITLE
Работа с формулами

### ISSUE THREAD

**Issue by arykovs** [llownall/wysiwygMath#2]
Дизайн: https://app.moqups.com/1LRSKsVGmW/view/page/aff6c8281

- [x] Заголовок "Вставить Формулу" заменить на "Вставить формулу"
- [x] Размер области, которая отводится под результат, надо немного увеличить по высоте и зафиксировать. Сейчас получается, что если я набираю формулу (например, такую x_{1,2}=\frac{-b\pm\sqrt{b^2-4ac}}{2a}) окно несколько увеличивается. Если я стираю форму - оно уменьшается. Выглядит не user friendly. В тоже время, если набирать большую формулу - она вроде масштабируется, чтобы вписаться, но окно всё равно «дергается», немного увеличиваясь.
- [x] Я не вижу ничего плохого в том, что появляющаяся область с готовыми символами будет перекрывать текст формулы, потому то предполагал, что сразу  после выбора символа это окно будет закрываться. Сейчас оно не закрывается, пока второй раз не нажмешь на кнопку, но я в этом смысла не вижу: если бы там была информация, которую нужно человеку вводить - тогда это имело бы смысл. А так оно просто висит без дела. Предлагаю закрывать сразу после выбора.
- [x] Каждый символ (в окне готовых символов) при наведении мышки должен «подсвечиваться» (или выделяться) квадратиком - чтобы было более ясно, на какой символ сейчас мышка указывает.
- [x] Для остальных спец. символов надо доделать  кнопки с соответствующими областями.- [ ] Появляющаяся область появляется слишком долго после клика на кнопке. Можно это немного ускорить?
- [x] Вставляться формула должна не в конец текста, а в текущее место курсора, как и любые другие символы. Это тем более актуально, что формулу не получается скопировать/вставить.
- [x] При двойном щелчке над существующей формулой должно открываться окно "Вставить формулу" с текстом этой формулы, чтобы пользователь мог его поменять.
- [x] Сейчас, когда я ввожу текст в поле ввода формулы, в поле "Результат" всё пропадает и как только я прекращаю вводить - там появляется результат. Давайте сделаем по другому: пока я ввожу новый текст, в поле "результат" сохраняется формула, которая была до момента, когда я начал ввод. Когда я ввод заканчиваю - поле "результат" обновляется. То есть: нет необходимости делать так, чтобы при каждом введенном символе поле результат обновлялось, но нужно сделать так, чтобы форму оттуда не исчезала, пока я ввожу новый текст.
- [x] Когда нажимаешь кнопки (над полем ввода формулы) - открывается область с выбором символов. Но закрывается она, только если ту же самую кнопку нажать. Давайте сделаем так, чтобы она закрывалась также, если мышкой кликнуть в любом месте вне этой области с символами (как любое контекстное меню).

**Comment by arykovs** [comment]
- [ ] Заголовок "Вставить Формулу" заменить на "Вставить формулу"
- [ ] Размер области, которая отводится под результат, надо немного увеличить по высоте и зафиксировать. Сейчас получается, что если я набираю формулу (например, такую x_{1,2}=\frac{-b\pm\sqrt{b^2-4ac}}{2a}) окно несколько увеличивается. Если я стираю форму - оно уменьшается. Выглядит не user friendly. В тоже время, если набирать большую формулу - она вроде масштабируется, чтобы вписаться, но окно всё равно «дергается», немного увеличиваясь.
- [ ] Я не вижу ничего плохого в том, что появляющаяся область с готовыми символами будет перекрывать текст формулы, потому то предполагал, что сразу  после выбора символа это окно будет закрываться. Сейчас оно не закрывается, пока второй раз не нажмешь на кнопку, но я в этом смысла не вижу: если бы там была информация, которую нужно человеку вводить - тогда это имело бы смысл. А так оно просто висит без дела. Предлагаю закрывать сразу после выбора.
- [ ] Появляющаяся область появляется слишком долго после клика на кнопке. Можно это немного ускорить?
- [ ] Каждый символ (в окне готовых символов) при наведении мышки должен «подсвечиваться» (или выделяться) квадратиком - чтобы было более ясно, на какой символ сейчас мышка указывает.
- [ ] Вставляться формула должна не в конец текста, а в текущее место курсора, как и любые другие символы. Это тем более актуально, что формулу не получается скопировать/вставить.
- [ ] При двойном щелчке над существующей формулой должно открываться окно "Вставить формулу" с текстом этой формулы, чтобы пользователь мог его поменять.
- [ ] Для остальных спец. символов надо доделать  кнопки с соответствующими областями.

**Comment by llownall** [comment]
> * [ ]  Появляющаяся область появляется слишком долго после клика на кнопке. Можно это немного ускорить?

Переключается display: none на display: grid по клику. Как сделать быстрее - идей нет. Возможно это потому, что в появляющейся сетке готовых формул много тегов mjx

> * [ ]  Вставляться формула должна не в конец текста, а в текущее место курсора, как и любые другие символы. Это тем более актуально, что формулу не получается скопировать/вставить.

Позиция курсора при наличии каких-либо тегов внутри contenteditable высчитывается неверно, и нередко формула добавляется прямо внутрь тега (например <di **сюда** v>)

**Comment by llownall** [comment]
> * [ ]  При двойном щелчке над существующей формулой должно открываться окно "Вставить формулу" с текстом этой формулы, чтобы пользователь мог его поменять.

Сейчас формула добавляется вовнутрь div, который contententeditable. Во vue для обработки клика на теге ставится директива v-on:click, но т.к. формула добавляется в DOM посредством javascript, vue не обрабатывает этот тег и при клике ничего не происходит

Мне кажется самое простое и не требующее костылей решение текущих проблем - форматировать текст в сыром виде и иметь возможность предпросмотра того, что получилось

**Comment by arykovs** [comment]
> Переключается display: none на display: grid по клику. Как сделать быстрее - идей нет. Возможно это потому, что в появляющейся сетке готовых формул много тегов mjx

ОК. Пока убираю. 

> Позиция курсора при наличии каких-либо тегов внутри contenteditable высчитывается неверно, и нередко формула добавляется прямо внутрь тега (например <di сюда v>)

Надо искать решение.
