### ISSUE TITLE
Исчезает тулбар

### ISSUE THREAD

**Issue by arykovs** [llownall/wysiwygMath#5]
Если в тексте выделить слово, а потоп на тулбаре нажать кнопку форматирования (B, допустим, или U) и удерживать её несколько секунд, то тулбар пропадает.
![Clipboard04](https://user-images.githubusercontent.com/20451590/96332939-02e81a80-1091-11eb-93e0-fc040697069c.jpg)

**Comment by arykovs** [comment]
Сейчас тестировал выравнивание по центру/левому/правому краю. Тулбар иногда пропадает, даже если не держать зажатой клавишу мыши долго, а кликнуть быстро, как это при обычной работе бывает.

**Comment by llownall** [comment]
Возможно проблема решена
