### ISSUE TITLE
Местоположение формул

### ISSUE THREAD

**Issue by arykovs** [llownall/wysiwygMath#6]
Кнопки управления положением (по центру, по левому/по правому краю) не работают для формул. Это проявляется в Chrome. В Firefox вроде работает.

**Comment by arykovs** [comment]
Это происходит не для всех формул. Например, если ввести y = f(x), то работает корректно. А если ввести y = f(x_1, x_2, ..., x_n) - то такая формула нормально не центрируется.

**Comment by llownall** [comment]
Исправил. До этого выравнивал document.execCommand, теперь ищу параграф и через css выравниваю его
