### ISSUE TITLE
Проблема с фокусом

### ISSUE THREAD

**Issue by arykovs** [llownall/wysiwygMath#7]
При нажатии любой кнопки на тулбаре происходит переход фокуса с текстового поля на тулбар и рамка вокруг текстового поля постоянно мигает. В то же время у того же Trumbowyg или в moqups ничего не мигает. Попробуйте разобраться и понять, насколько сложно это исправить. Это не критично - в том же github оно тоже мигает - поэтому пока можно оставить как есть и не тратить на это много времени. Но в целом это не очень удобно для пользователя.

**Comment by arykovs** [comment]
Фокус уходит из поля ввода: если в поле ввода выделить слово и нажать, допустим, кнопку B, то слово выделится жирным и фокус вернется обратно в поле ввода (так и должно быть). Если же в поле ввода ввести какой-то текст, а потом нажать на тулбаре кнопку, допустим - B, не выделяя ничего в поле ввода, то фокус остается на тулбаре, а должен возвращаться на поле ввода.

**Comment by llownall** [comment]
Исправил

**Comment by arykovs** [comment]
- [x] Не работает для выбора размера шрифта. Фокус не возвращается, а если его вернуть кликом в область ввода - то сбрасывается выбранный размер шрифта на стандартный. Надо это проверить для всех кнопок. Фокус всегда должен возвращаться на поле ввода.
