### ISSUE TITLE
Размер шрифта

### ISSUE THREAD

**Issue by arykovs** [llownall/wysiwygMath#9]
- [x] Открываю тестовую страницу. По умолчанию в редакторе стоит 12pt. Выбираю 18pt. Начинаю вводить текст - он все равно вводится 12pt. На тулбаре тоже скидывается на 12pt.
- [x] При вводе текста 12pt между строками есть определенное расстояние. Если затем увеличить размер до 24pt (допустим), то вместе с размером шрифта увеличится и расстояние между строками - так и должно быть. Далее, если выбрать размер шрифта обратно 12pt, то шрифт уменьшится, а вот расстояние между новыми строками будет оставаться, как будто шрифт 24pt.

**Comment by arykovs** [comment]
- Добавляю новый вопрос. Начинаю вводить текст (он набирается 12pt). Выбираю размер 18pt - увеличивается отступ от верхней строки, на тулбаре светится 18pt, но текст продолжает набираться шрифтом 12pt.  Далее это можно повторить - выбрать шрифт, допустим, 24pt - и продолжать набирать текст - он будет набираться 12pt.
- Добавляю новый вопрос. Начинаю набирать текст шрифтом 12pt, например, 10 символов. Дальше выделяю весь введенный текст и выбираю шрифт 24pt - размер шрифта не меняется. При этом, если снять выделение, потом опять выделить этот же текст и изменить шрифт на 24pt - все срабатывает как надо.

**Comment by llownall** [comment]
Исправлено в [коммите 160f34c](https://github.com/arykovs/iAudience/commit/160f34c59cdb3b625516d61f292112b6f383cff1)

**Comment by arykovs** [comment]
- Ввожу текст шрифтом по умолчанию. Затем на тулбаре выбирают другой шрифт, допустим, 24pt. Мигающий курсор из текстового поля пропадает. Он появится там только после того, как я какой-то символ введу. Нужно чтобы он все время был. Аналогичная проблема есть при вставке формулы: когда формула вставляется в окно, курсор пропадает и не видно, где появится следующая буква 
- ввожу текст шрифтом по умолчанию. Переключаю на тулбаре шрифт на 24pt. ввожу текст дальше. второй раз переключаю шрифт на 36pt - после его выбора на тулбаре продолжает показываться 24pt. если я введу символ - он покажется правильным размером и дальше на тулбаре тоже отобразится верный размер. Но он должен сразу верный показываться. Если второй, третий и т.д. разы дальше менять шрифт - то та же проблема.
